---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    exclude_fingerprints:
    - 88b89a5c35290dce4488a14d6b861e85 # Similar code for child parent finding
    - e7c67c8a24ff4bafbb977349b5a47266 # Similar exception code for parent/child in api org units controller
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - 1800b7dde7bb9294e06a5b85c19c138b
    - 8783d3d9e80ed734768fbdb29422ad44 # Parameters > 5 in register ingester method
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- test/
- vendor/
