# Welcome to Jekyll!
#

# Site settings
title: DMA Online
description: |
  Research data management made easy
owner: Lancaster University Library
first_published: 2016 # if migrating another site, the year of your first publish
email: library.dit@lancaster.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lulibrary.github.com/DMAO" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/LancasterUniLib
  github: https://github.com/lulibrary
  facebook-official: https://facebook.com/<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
