default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: stephenrobinson

development:
  <<: *default
  database: dmao_development

test:
  <<: *default
  database: dmao_test

production:
  <<: *default
  database: dmao_prod
